# Generated by Django 4.1.4 on 2022-12-26 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkInfo',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=30)),
                ('domain', models.CharField(choices=[('short.ly', 'short.ly')], default='short.ly', max_length=20)),
                ('custom_half', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
